{
 "title": "mySQL-connector",
 "tags": [ "Mysql" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ds: mysql",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT name, SUM(units) FROM db1.products GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "All DB Total Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "##Space occupied by each database\n\nSELECT table_schema AS \"Database\",  SUM(data_length + index_length) / 1024 / 1024 AS \"Size (MB)\"  FROM information_schema.TABLES  GROUP BY table_schema;\n\n"
    }
   ]
  },
  {
   "title": "Total Units Sold",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT name, SUM(units) FROM db1.products GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "ds: mysql",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT name, SUM(units) FROM db1.products WHERE name NOT LIKE '%drill%' GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "ds: mysql",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT name, SUM(units) FROM db1.products GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Builder - groupie",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT name, COUNT(units) FROM db1.products GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Histogram bucket of 20",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "db1",
     "rawSql": "SELECT units FROM db1.products LIMIT 50 "
    }
   ]
  }
 ]
}