{
 "title": "Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "panels": [
  {
   "title": "PromQL example Gauge threshold uses Relative Time now-10m",
   "type": "gauge",
   "description": "relative uses its own timeframe and not the time filter dropdown",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PromQL example Gauge threshold without  Relative Time ",
   "type": "gauge",
   "description": "it uses the time filter dropdown",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Stats - 2 queries in one panel",
   "type": "timeseries",
   "description": "Total and Free memory",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "__auto" }
   ]
  }
 ]
}